services:
  db:
    image: pgvector/pgvector:0.8.1-pg18-trixie
    container_name: voice-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql

  redis:
    image: redis:8-trixie
    container_name: voice-redis
    ports:
      - "6379:6379"
    restart: always

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  postgres_data:
